import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const packageJsonPath = resolve(repoRoot, "package.json");
const generatedDir = resolve(repoRoot, "plugin", "_generated");
const generatedFile = resolve(generatedDir, "version.generated.ts");
const runtimePackageDir = resolve(repoRoot, "build", "plugin");
const runtimePackageFile = resolve(runtimePackageDir, "package.json");

function readVersion() {
  const raw = readFileSync(packageJsonPath, "utf8");
  const parsed = JSON.parse(raw);
  if (typeof parsed.version !== "string" || parsed.version.length === 0) {
    throw new Error(
      `package.json at ${packageJsonPath} has no valid "version" string`,
    );
  }
  return parsed.version;
}

function writeVersionModule(version) {
  if (!existsSync(generatedDir)) {
    mkdirSync(generatedDir, { recursive: true });
  }
  const body = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.\n// Re-run \`npm run build:plugin\` to refresh.\nexport const PLUGIN_VERSION: string = ${JSON.stringify(version)};\n`;
  writeFileSync(generatedFile, body, "utf8");
}

function writeRuntimeModuleBoundary() {
  mkdirSync(runtimePackageDir, { recursive: true });
  // OpenCode's host package is ESM, while tsc emits CommonJS for the MCP runtime.
  // This nested manifest keeps Node's module interpretation stable after bundling.
  writeFileSync(runtimePackageFile, '{"type":"commonjs"}\n', "utf8");
}

const version = readVersion();
writeVersionModule(version);
writeRuntimeModuleBoundary();
console.log(`[generate-version] wrote ${generatedFile} (version=${version})`);
